site_name: Eric Nemchik
site_url: https://nemchik.com
site_author: Eric Nemchik
site_description: I'm a techie who loves to code.

repo_name: nemchik/nemchik
repo_url: https://github.com/nemchik/nemchik

copyright: Copyright &copy; 2022 Eric Nemchik

theme:
  name: material
  include_search_page: false
  search_index_only: true
  language: en
  features:
    - navigation.instant
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: blue grey
      accent: red
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: blue grey
      accent: red
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
  favicon: images/favicon.ico
  logo: images/android-chrome-512x512.png

plugins:
  # - search
  - redirects:
      redirect_maps:
        s/facebook.md: https://facebook.com/nemchik
        s/github.md: https://github.com/nemchik
        s/gitlab.md: https://gitlab.com/nemchik
        s/linkedin.md: https://linkedin.com/in/nemchik
        s/twitter.md: https://twitter.com/NemchikEric
        u/buyshared.md: https://my.frantech.ca/aff.php?aff=1555&site=buyshared
        u/buyvm.md: https://my.frantech.ca/aff.php?aff=1555&site=buyvm
  - minify:
      minify_html: true

extra:
  analytics:
    provider: google
    property: G-GBKLVHZFR3
  social:
    - icon: fontawesome/brands/square-facebook
      link: https://facebook.com/nemchik
    - icon: fontawesome/brands/square-github
      link: https://github.com/nemchik
    - icon: fontawesome/brands/gitlab-square
      link: https://gitlab.com/nemchik
    - icon: fontawesome/brands/linkedin
      link: https://linkedin.com/in/nemchik
    - icon: fontawesome/brands/square-twitter
      link: https://twitter.com/NemchikEric
nav:
  - About Me: index.md
