---
name: Build mkdocs and deploy to GitHub Pages

on: [push, pull_request]

jobs:

  build:
    name: Build docs
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.1.1
        with:
          fetch-depth: 0
          sparse-checkout: |
            docs
      - uses: actions/setup-python@v5.0.0
        with:
          python-version: 3.x
      - id: pip-cache
        run: |
          echo "dir=$(pip cache dir)" >> $GITHUB_OUTPUT
      - uses: actions/cache@v4.0.0
        with:
          path: ${{ steps.pip-cache.outputs.dir }}
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-
      - run: pip install -r docs/requirements.txt
      - run: mkdocs build

  deploy:
    if: github.event_name == 'push' && contains(fromJson('["refs/heads/master", "refs/heads/main"]'), github.ref)
    needs: build
    name: Deploy docs
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.1.1
        with:
          fetch-depth: 0
          sparse-checkout: |
            docs
      - uses: actions/setup-python@v5.0.0
        with:
          python-version: 3.x
      - id: pip-cache
        run: |
          echo "dir=$(pip cache dir)" >> $GITHUB_OUTPUT
      - uses: actions/cache@v4.0.0
        with:
          path: ${{ steps.pip-cache.outputs.dir }}
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-
      - run: pip install -r docs/requirements.txt
      - run: mkdocs gh-deploy --force
