name: Publish docs via GitHub Pages

on:
  push:
    branches:
      - master

jobs:
  build:
    name: Deploy docs
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.3.2

      # - run: cp README.md docs/index.md

      - uses: actions/setup-python@v2
        with:
          python-version: 3.x

      - run: pip install mkdocs-material

      - run: mkdocs gh-deploy --force
